# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Silo Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for Silo Test
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FacebookLogin'
  pod 'SDWebImage'
  
  target 'Silo TestTests' do
    inherit! :search_paths
    # Pods for testing
  end
  
  target 'Silo TestUITests' do
    # Pods for testing
  end
  
end
